services:
  dev-db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - miasin
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - dev-db
networks:
  miasin:
volumes:
  postgres:
healthcheck:
  test: ["CMD-SHELL", "pg_isready -U postgres"]
  interval: 10s
  timeout: 5s
  retries: 3
