services:
  dev-db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - miasin
networks:
  miasin:
volumes:
  postgres-data:
