services:
  dev-db:
    image: postgres:15
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - miasin
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - dev-db
    networks:
      - miasin

networks:
  miasin:

volumes:
  postgres:
